apiVersion: v1
kind: Service
metadata:
  name: ecosync-backend
  namespace: ecosync
spec:
  selector:
    app: ecosync-backend
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP
