apiVersion: v1
kind: Secret
metadata:
  name: ecosync-secrets
  namespace: ecosync
type: Opaque
stringData:
  JWT_SECRET: "change_me"
  LINK_TOKEN_SECRET: "change_me"
  MONGODB_URI: "mongodb://mongo:27017/ecosync"
  REDIS_URL: "redis://redis:6379"
